name: Lint

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm i
      run: npm i
    - name: npm run lint
      run: npm run lint
